defaults: &defaults
  working_directory: ~/app

version: 2
jobs:
  install:
    <<: *defaults
    docker:
      - image: circleci/node:6.11.5
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  test:
    <<: *defaults
    docker:
      - image: circleci/node:6.11.5
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: npm t
      - run:
          name: Lint code
          command: npm run lint
  publish:
    <<: *defaults
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Set NPM tokens
          command: echo -e $NPMRC > ~/.npmrc
      - run:
          name: Publish to NPM
          command: npx published

workflows:
  version: 2
  ci-cd:
    jobs:
      - install
      - test:
          requires:
            - install
      - publish:
          context: org-global
          requires:
            - test
          filters:
            branches:
              only:
                - master
